### ISSUE TITLE
split of HTML spec on 'elements of html' is too large

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/html-tools#2]
The page http://w3c.github.io/html/semantics.html#semantics regularly causes my browser to freeze, (Firefox 43 on windows 10).
Can we break this page into smaller pages?

**Comment by plehegar** [comment]
We certainly can. However, it does load reasonably on my side (~3s) so I'm wondering if others are experiencing the same issue as you are.

**Comment by plehegar** [comment]
Reclassified as a bug to be fixed.

**Comment by chaals** [comment]
A suggested split: 
- up to and including 4.6 - so text and structure elements
- 4.7, embedded things and 4.8 links
- 4.9 and 4.10 tables and forms
the rest…

This is really arbitrary, but tries to make logical chunks of rational size...

**Comment by travisleithead** [comment]
Closing this, as I think the semantics section is already split-up--at least it appears differently than it did before (semantics.html is very tiny now).
